[project]
name = "service3"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "langchain-core>=1.6.5",
    "langchain-openai>=1.6.6",
    "langchain-postgres>=0.0.18",
    "openai>=3.20.0",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.54.0",
]
